repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: system
        entry: shellcheck --severity=error
        types: [shell]

      - id: markdownlint
        name: markdownlint
        language: system
        entry: markdownlint-cli2
        types: [markdown]

      - id: nixfmt
        name: nixfmt
        language: system
        entry: nixfmt
        types: [file]
        files: \.nix$
