#!/usr/bin/env bash
# Setup Agent SSH Keys
#
# Generates platform-specific SSH keys for agent operations and provides
# instructions for adding them as deploy keys to repositories.
#
# Usage: setup-agent-keys.sh

set -euo pipefail

AGENT_KEY_DIR="$HOME/.ssh"
GITHUB_KEY="$AGENT_KEY_DIR/agent-github"
GITLAB_KEY="$AGENT_KEY_DIR/agent-gitlab"
GITEA_KEY="$AGENT_KEY_DIR/agent-gitea"

echo "======================================"
echo "Agent SSH Key Setup"
echo "======================================"
echo ""

# Early exit if not in a git repo
if ! git remote -v &>/dev/null 2>&1; then
  echo "✓ Agent SSH keys verified (not a git repo)"
  exit 0
fi

# Early exit if key already exists for this platform
remote_url=$(git remote get-url origin 2>/dev/null || echo "")
if [[ "$remote_url" =~ github\.com ]] && [[ -f "$GITHUB_KEY" ]]; then
  echo "✓ Agent SSH keys verified (GitHub key exists)"
  exit 0
elif [[ "$remote_url" =~ gitlab\.com ]] && [[ -f "$GITLAB_KEY" ]]; then
  echo "✓ Agent SSH keys verified (GitLab key exists)"
  exit 0
elif [[ "$remote_url" =~ gitea ]] && [[ -f "$GITEA_KEY" ]]; then
  echo "✓ Agent SSH keys verified (Gitea key exists)"
  exit 0
fi

# Detect current repository
CURRENT_REPO=""
CURRENT_PLATFORM=""
CURRENT_KEY=""

if git remote -v &>/dev/null; then
  REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
  if [[ -n "$REMOTE_URL" ]]; then
    CURRENT_REPO="$REMOTE_URL"
    
    # Detect platform
    if [[ "$REMOTE_URL" =~ github\.com[:/]([^/]+)/([^/\.]+) ]]; then
      CURRENT_PLATFORM="github"
      CURRENT_KEY="$GITHUB_KEY"
      REPO_OWNER="${BASH_REMATCH[1]}"
      REPO_NAME="${BASH_REMATCH[2]}"
    elif [[ "$REMOTE_URL" =~ gitlab\.com[:/]([^/]+)/([^/\.]+) ]]; then
      CURRENT_PLATFORM="gitlab"
      CURRENT_KEY="$GITLAB_KEY"
      REPO_OWNER="${BASH_REMATCH[1]}"
      REPO_NAME="${BASH_REMATCH[2]}"
    elif [[ "$REMOTE_URL" =~ gitea ]]; then
      CURRENT_PLATFORM="gitea"
      CURRENT_KEY="$GITEA_KEY"
      # Try to extract owner/repo from various gitea URL formats
      if [[ "$REMOTE_URL" =~ [:/]([^/]+)/([^/\.]+)\.git ]]; then
        REPO_OWNER="${BASH_REMATCH[1]}"
        REPO_NAME="${BASH_REMATCH[2]}"
      fi
    fi
  fi
fi

# Function to generate key if it doesn't exist
generate_key() {
  local key_path="$1"
  local platform="$2"
  
  if [[ -f "$key_path" ]]; then
    echo "✓ Key already exists: $key_path"
    return 0
  fi
  
  echo "Generating $platform agent key..."
  ssh-keygen -t ed25519 -f "$key_path" -C "llm-agent@$platform" -N ""
  echo "✓ Generated: $key_path"
}

# Generate keys for all platforms
echo "1. Generating Agent SSH Keys"
echo "------------------------------"
generate_key "$GITHUB_KEY" "github"
generate_key "$GITLAB_KEY" "gitlab"
generate_key "$GITEA_KEY" "gitea"
echo ""

# Create SSH config if it doesn't exist or update it
SSH_CONFIG="$HOME/.ssh/config"
SSH_CONFIG_AGENT="$HOME/.ssh/config.agent"

echo "2. Configuring SSH"
echo "------------------------------"

# Create agent-specific config
cat > "$SSH_CONFIG_AGENT" << 'EOF'
# Agent SSH Configuration
# Auto-generated by setup-agent-keys.sh

Host github.com
  IdentityFile ~/.ssh/agent-github
  IdentitiesOnly yes

Host gitlab.com
  IdentityFile ~/.ssh/agent-gitlab
  IdentitiesOnly yes

Host *.gitea.* gitea.*
  IdentityFile ~/.ssh/agent-gitea
  IdentitiesOnly yes
EOF

echo "✓ Created: $SSH_CONFIG_AGENT"

# Check if main SSH config includes agent config
if [[ -f "$SSH_CONFIG" ]]; then
  if ! grep -q "config.agent" "$SSH_CONFIG"; then
    echo ""
    echo "⚠️  Add this line to the TOP of your ~/.ssh/config:"
    echo ""
    echo "    Include config.agent"
    echo ""
    read -p "Press Enter to continue..."
  else
    echo "✓ SSH config already includes agent config"
  fi
else
  echo "Include config.agent" > "$SSH_CONFIG"
  chmod 600 "$SSH_CONFIG"
  echo "✓ Created: $SSH_CONFIG"
fi
echo ""

# Update sandbox to mount agent keys
echo "3. Updating Sandbox Configuration"
echo "------------------------------"

SANDBOX_SCRIPT="$(dirname "$0")/agent-sandbox.sh"

if [[ -f "$SANDBOX_SCRIPT" ]]; then
  # Check if agent SSH keys are already mounted
  if ! grep -q "agent-github" "$SANDBOX_SCRIPT"; then
    echo "Adding agent SSH key mounts to sandbox script..."
    
    # Find the line with "Optional: bind mount SSH keys"
    # Insert agent key mounts before it
    sed -i '/# Optional: bind mount SSH keys for git authentication/i \
# Agent SSH keys for git operations\
if [[ -f "$HOME/.ssh/agent-github" ]]; then\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/agent-github" "$HOME/.ssh/agent-github")\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/agent-github.pub" "$HOME/.ssh/agent-github.pub")\
fi\
if [[ -f "$HOME/.ssh/agent-gitlab" ]]; then\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/agent-gitlab" "$HOME/.ssh/agent-gitlab")\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/agent-gitlab.pub" "$HOME/.ssh/agent-gitlab.pub")\
fi\
if [[ -f "$HOME/.ssh/agent-gitea" ]]; then\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/agent-gitea" "$HOME/.ssh/agent-gitea")\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/agent-gitea.pub" "$HOME/.ssh/agent-gitea.pub")\
fi\
\
# SSH config for agent keys\
if [[ -f "$HOME/.ssh/config.agent" ]]; then\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/config.agent" "$HOME/.ssh/config.agent")\
fi\
if [[ -f "$HOME/.ssh/config" ]]; then\
  BWRAP_ARGS+=(--ro-bind "$HOME/.ssh/config" "$HOME/.ssh/config")\
fi\
\
' "$SANDBOX_SCRIPT"
    
    echo "✓ Updated: $SANDBOX_SCRIPT"
    echo "  (Agent keys now accessible in sandbox)"
  else
    echo "✓ Sandbox already configured for agent keys"
  fi
else
  echo "⚠️  Sandbox script not found: $SANDBOX_SCRIPT"
fi
echo ""

# Provide instructions for current repository
if [[ -n "$CURRENT_REPO" ]] && [[ -n "$CURRENT_PLATFORM" ]]; then
  echo "4. Add Deploy Key to Current Repository"
  echo "======================================"
  echo ""
  echo "Repository: $CURRENT_REPO"
  echo "Platform:   $CURRENT_PLATFORM"
  echo ""
  echo "Public Key to Add:"
  echo "-------------------"
  cat "${CURRENT_KEY}.pub"
  echo ""
  echo "Instructions:"
  echo "-------------"
  
  case "$CURRENT_PLATFORM" in
    github)
      echo "1. Go to: https://github.com/$REPO_OWNER/$REPO_NAME/settings/keys"
      echo "2. Click 'Add deploy key'"
      echo "3. Title: LLM Agent"
      echo "4. Key: (copy the public key above)"
      echo "5. ☑ Allow write access"
      echo "6. Click 'Add key'"
      echo ""
      echo "Or use GitHub CLI:"
      echo "  gh repo deploy-key add ${CURRENT_KEY}.pub --title 'LLM Agent' --allow-write"
      ;;
    gitlab)
      echo "1. Go to: https://gitlab.com/$REPO_OWNER/$REPO_NAME/-/settings/repository"
      echo "2. Expand 'Deploy Keys'"
      echo "3. Title: LLM Agent"
      echo "4. Key: (copy the public key above)"
      echo "5. ☑ Write access allowed"
      echo "6. Click 'Add key'"
      ;;
    gitea)
      echo "1. Go to your Gitea repository settings"
      echo "2. Navigate to 'Deploy Keys'"
      echo "3. Title: LLM Agent"
      echo "4. Key: (copy the public key above)"
      echo "5. ☑ Allow write access (if available)"
      echo "6. Click 'Add key'"
      ;;
  esac
  
  echo ""
  echo "After adding the deploy key, test with:"
  echo "  git push"
  echo ""
else
  echo "4. Add Deploy Keys to Repositories"
  echo "======================================"
  echo ""
  echo "Not in a git repository or remote not configured."
  echo ""
  echo "For each repository you want agents to access:"
  echo ""
  echo "GitHub:"
  echo "  Repository → Settings → Deploy Keys → Add deploy key"
  echo "  Use key: $GITHUB_KEY.pub"
  echo ""
  echo "GitLab:"
  echo "  Project → Settings → Repository → Deploy Keys → Add deploy key"
  echo "  Use key: $GITLAB_KEY.pub"
  echo ""
  echo "Gitea:"
  echo "  Repository → Settings → Deploy Keys → Add deploy key"
  echo "  Use key: $GITEA_KEY.pub"
  echo ""
fi

echo "======================================"
echo "Setup Complete!"
echo "======================================"
